mule:
  env: "dev"

secure:
  properties:
    key: "${env.SECURE_PROPERTIES_KEY}"

http:
  host: "0.0.0.0"
  port: "8081"

external:
  api:
    protocol: "https"
    host: "jsonplaceholder.typicode.com"
    port: "443"
    resourcePath: "/users"
