mule:
  env: "dev"

http:
  host: "0.0.0.0"
  port: "8081"

external:
  api:
    host: "jsonplaceholder.typicode.com"
    port: "443"
    resourcePath: "/users"
    clientId: "replace-me"
    clientSecret: "replace-me"
